import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/lib/lenis";
import Web3ModalProvider from "@/context";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body className={`${inter.className} antialiased`}>
          <Web3ModalProvider>
            <Navbar />
            {children}
          </Web3ModalProvider>
        </body>
      </ReactLenis>
    </html>
  );
}
